# Generated by Django 2.2.7 on 2020-01-07 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(max_length=50, verbose_name='Colaborador')),
                ('uid', models.CharField(max_length=8, verbose_name='UID do cartão RFID')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='Horario')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponto.Colaboradores', verbose_name='Colaborador')),
            ],
        ),
    ]
